### ISSUE TITLE
Local testing story

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/node-tokens#2]
Right now there is no easy way to test an application that uses `node-tokens` because it expects `CREDENTIALS_DIR` and OAuth providers and what not.

**Comment by hjacobs** [comment]
You could/should use the same approach as the Java and Python tokens libraries: they allow setting fixed tokens with OAUTH2_ACCESS_TOKENS, see https://github.com/zalando-stups/tokens#local-testing
