### ISSUE TITLE
100 % test coverage

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/node-tokens#6]
Only line 180 of `default.js` is missing! We can do this!

https://coveralls.io/files/1623087880#L180

**Comment by hjacobs** [comment]
:clap:

**Comment by prayerslayer** [comment]
Fixed with commit 16796338680e2b784506a99b5177dafafd5f2e7d!

![image](https://cloud.githubusercontent.com/assets/878512/11740404/8b579216-9ff2-11e5-8db4-8ef58e83fc5c.png)
